<style>
  .overlay {
    height: 100%;
    width: 100%;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: rgba(0, 0, 0, 0.4);
    overflow-x: hidden;
    transition: 0.5s;
  }

  .overlay-content {
    position: relative;
    top: 50%;
    left: 6%;
    width: 100%;
    text-align: center;
    margin-top: 30px;
  }

  .overlay a {
    padding: 8px;
    text-decoration: none;
    font-size: 36px;
    color: #818181;
    display: block;
    transition: 0.3s;
  }

  .overlay a:hover,
  .overlay a:focus {
    color: #f1f1f1;
  }

  .overlay .closebtn {
    position: absolute;
    top: 20px;
    right: 45px;
    font-size: 60px;
  }

  .rotate-center {
    -webkit-animation: rotate-center 0.6s linear infinite both;
    animation: rotate-center 0.6s linear infinite both;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2022-5-12 12:42:7
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */
  @-webkit-keyframes rotate-center {
    0% {
      -webkit-transform: rotate(0);
      transform: rotate(0);
    }

    100% {
      -webkit-transform: rotate(360deg);
      transform: rotate(360deg);
    }
  }

  @keyframes rotate-center {
    0% {
      -webkit-transform: rotate(0);
      transform: rotate(0);
    }

    100% {
      -webkit-transform: rotate(360deg);
      transform: rotate(360deg);
    }
  }

  @media screen and (max-height: 450px) {
    .overlay a {
      font-size: 20px
    }

    .overlay .closebtn {
      font-size: 40px;
      top: 15px;
      right: 35px;
    }
  }

</style>

<div id="loading_screen" class="overlay d-none">
  <div class="overlay-content">
    <img src="https://img.icons8.com/fluency/96/000000/spinner-frame-1.png" class="rotate-center" />
  </div>
</div>
